### ISSUE TITLE
Support for 2016 and deployment without multi tenet environment

### ISSUE THREAD

**Issue by tsheth** [deep-security/ansible#11]
Hi,

  Can we have windows 2016 support in windows? also i have noticed that current ansible is designed for multi-tenet deployment. Can we have the palybook created for non-multi-tenant DSM deployments?

**Comment by DeepSecurityOpenSourceSupport** [comment]
Hi @tsheth ,

Thanks for using our playbook.

This playbook was verified on various platforms, including Windows 2016.
However, we couldn't update the support list as Ansible Galaxy only offer 2012R2 for windows:
https://galaxy.ansible.com/api/v1/platforms/

About the multi-tenant part, really sorry for the confusing, our playbook is not limited to multi-tenant deployment only.
You can use it without "tenant_id", and your DSA will be activated to T0, which is used by the non-multi-tenant DSM deployments.
We'll create an internal case to update the document to avoid the confusing afterward.

Please let us know if you encounter any problem.

Best Regards,
Deep Security Open Source Support team

**Comment by DeepSecurityOpenSourceSupport** [comment]
Hi @tsheth,

We've updated the README to address the support for non-multi-tenant DeepSecurity Manager.
Please let us know if you have other concerns.

Best Regards,
James
