### ISSUE TITLE
Cannot detect OS from inventory

### ISSUE THREAD

**Issue by mdufresn** [deep-security/ansible#17]
Hello folks,

I've a problem during implementation of the DeepSec playbook provide on this repository.
Maybe you could help me, cause i'm not an expert with Trend Micro and Ansible.

For the "hosts" variable, I've precise many device reachable from my Ansible server.
But during the execution of the playbook the task stops on : 
![image](https://user-images.githubusercontent.com/39830744/41661993-550c3916-74a0-11e8-938e-6de7360679a6.png)

Even the host is windows hosts this error stays the same.
I've missed something ?

It works only when the hosts is the Deep Security Manager : it'll install the agent and activate it... 

Thanks in advance guys.

**Comment by harrisonchen201703** [comment]
Hi, @mdufresn 
Thanks for opening a ticket to us, that will be really helpful if we understand more on how users will integrated our playbook with their own project.

Before we decide to take any action, we might want to know more on this story:
1. May i have your help to check if your vm that plans to install Deep security Agents is available to connect with Deep Security Manager? Which this playbook will help you to download agent package from your Deep Security Manager.

2. Also, can you please check if the platform you're going to install Agent has the corresponding package on the Deep security Manager? 
It can be checked from: Administrator -> Update -> Software -> Local

3. Also, if you're not using the default playbook, can you please share the playbook and inventory file you're using now for further investigation?

Thanks.

**Comment by DeepSecurityOpenSourceSupport** [comment]
Hi @mdufresn ,

We might not go for further troubleshooting as there are a lot of missing information.
Please contact us by sending an email to deepsecurityopensource@trendmicro.com with the information @harrisonchen201703 is requesting, so we can help you go forward on the path to use our playbook.

Best Regards,
Deep Security Open Source Support team
