### ISSUE TITLE
error when running the playbook

### ISSUE THREAD

**Issue by k1m0n3** [deep-security/ansible#20]
Hello,

I got this error when i start the playbook.
The offending line appears to be:

  roles:
    - role: deep-security.deep-security-agent
      ^ here

I'm new with ansible, and would like to understand this error please

Thanks.

**Comment by harrisonchen201703** [comment]
Hi, Kim0n3
The example in README file is assumed that users may have downloaded the source from Ansible Galaxy first, please downloaded the source by following the instruction:
`ansible-galaxy install deep-security.deep-security-agent`
And also, please don't forget the indent before executing the playbook.

Please let us know if there's anything we did not mention here.
Thank you.

**Comment by k1m0n3** [comment]
Extact, thanks :)
