### ISSUE TITLE
Possible to have more administrative functionality?

### ISSUE THREAD

**Issue by aodj** [deep-security/ansible#6]
Is it possible to include more administrative functionality such as uninstallation or disabling of the agent? There already exist plenty of tasks dedicated to finding the agent install location across all platforms and it could be smart to extend this.

**Comment by DeepSecurityOpenSourceSupport** [comment]
Hi @aodj ,

Sorry for the late responding, I'm not sure why the watch function on git was not worked as expected.
But we've seen your suggestion now and will have some internal discussion on the request.

Best Regards,
Deep Security Open Source Support team

**Comment by DeepSecurityOpenSourceSupport** [comment]
Hi @aodj ,

We've done some internal discussion, but actually we're not so sure about the use case to use Ansible to uninstall/disable DeepSecurity Agent.
Could you provide us more detail scenario so that we can evaluate it more properly?

Besides, if you already know how to adjust it, you may create a PR and we can help to review/merge/publish to galexy accordingly.

Best Regards,
Deep Security Open Source Support team

**Comment by aodj** [comment]
As an example, whilst testing out Deep Security at work, we used the Ansible scripts in this repository to deploy the agent. That went well, all the detection was accurate and everything worked as intended. After the test, I had to go in and remove the agent from the individual instances manually, rather than making continued use of the Ansible scripts (since they were insufficient).

It's no a problem to write a simple extension to our own Ansible tooling that simply invokes `yum uninstall` but I can't upstream any changes, since I don't have any testing capabilities for the alternative operating systems that your tooling supports (Windows, Debian, etc). So I can make a PR that supports RHEL or CentOS, but then I would expect it to be rejected, which is why I suggested you do it, since I would assume you have the testing capabilities, and you've already written some boilerplate code for finding the agent and invoking it using the correct package manager.

It later occurred to me that I might be able to disable/unregister the agent with these tools, instead of removing it entirely, since the command line options detail a `-r/--reset` [option](https://help.deepsecurity.trendmicro.com/10_3/aws/command-line-utilities.html) however that isn't exposed in the commands available in [`manage.yml`](https://github.com/deep-security/ansible/blob/master/tasks/manage.yml).

**Comment by DeepSecurityOpenSourceSupport** [comment]
Hi @aodj , 
We have another internal discussion today, and we think it would be better for us to know more detail about your request to provide better solution.
Please contact with us via email deepsecurityopensource@trendmicro.com.
Thanks for trying our script and hope we can fulfill your request.

Best Regards,
Deep Security Open Source Support team
