### ISSUE TITLE
[WARNING]: Found variable using reserved name: action

### ISSUE THREAD

**Issue by conlon** [deep-security/ansible#9]
Using ansible 2.4.3.0, I get this warning message every time I use this role.

Recommend changing `action` to: operation, process, or some other synonym that's not a reserved name in ansible.

**Comment by DeepSecurityOpenSourceSupport** [comment]
Hi @conlon ,

Thanks for your finding, we'll follow this up.

Best Regards,
Deep Security Open Source Support team

**Comment by harrisonchen201703** [comment]
Hi, @conlon,
Thanks for your advice, unfortunately we could not reproduce this issue on our side.
Ansible --version:
```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```
May i have your help to describe how to reproduce this issue?
Thanks.

**Comment by DeepSecurityOpenSourceSupport** [comment]
Hi @conlon ,

We've converted the variable name from 'action' to 'operation'
Please let us know if you have other concerns.

Best Regards,
Deep Security Open Source Support team
